name: Build and Release Android APK

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build debug APK
      run: ./gradlew assembleDebug
      
    - name: Build release APK
      run: ./gradlew assembleRelease
      
    - name: Get version name
      id: version
      run: |
        VERSION=$(grep "versionName" app/build.gradle | sed 's/.*"\(.*\)".*/\1/')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Rename APK files
      run: |
        cp app/build/outputs/apk/debug/app-debug.apk copilot-android-client-v${{ steps.version.outputs.version }}-debug.apk
        cp app/build/outputs/apk/release/app-release-unsigned.apk copilot-android-client-v${{ steps.version.outputs.version }}.apk
      
    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: copilot-android-client-debug
        path: copilot-android-client-v${{ steps.version.outputs.version }}-debug.apk
        
    - name: Upload Release APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: copilot-android-client-release
        path: copilot-android-client-v${{ steps.version.outputs.version }}.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: "Copilot Android Client v${{ steps.version.outputs.version }}"
        body: |
          ## 📱 Copilot Android Client v${{ steps.version.outputs.version }}
          
          ### 🚀 What's New
          - Latest features and improvements
          - Bug fixes and performance enhancements
          - Updated dependencies and security patches
          
          ### 📥 Download
          - **copilot-android-client-v${{ steps.version.outputs.version }}.apk** - Main release APK
          - **copilot-android-client-v${{ steps.version.outputs.version }}-debug.apk** - Debug version with additional logging
          
          ### 📋 Requirements
          - Android 12 (API 31) or higher
          - Internet connection for server communication
          - Server setup (included in repository)
          
          ### 🔧 Installation
          1. Download the APK file
          2. Enable "Install from unknown sources" in Android settings
          3. Install the APK
          4. Configure your server connection in the app
          
          ### 🆕 Features in this version
          - Multi-server support with easy switching
          - Dark mode with system auto-detection
          - Chat history with per-server isolation
          - Automatic update checking
          - Offline help documentation
          - Common keystroke shortcuts
          - Network auto-discovery
          
          See the [README](https://github.com/ssfdre38/copilot-android-client/blob/main/README.md) for full setup instructions.
        files: |
          copilot-android-client-v${{ steps.version.outputs.version }}.apk
          copilot-android-client-v${{ steps.version.outputs.version }}-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}